/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserHome;

import static database.db.con;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Bilal
 */
public class showStudent extends javax.swing.JFrame {

    /**
     * Creates new form showStudent
     */
    public showStudent() {
        initComponents();
        Toolkit tool= getToolkit();
        Dimension size=tool.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }

    public void showStudent1() {

        try {
            
            DefaultTableModel dm = (DefaultTableModel) jTableShowStudent.getModel();
              while (dm.getRowCount() > 0) {
                dm.removeRow(0);
              }

            String qury = "SELECT * FROM student";
            PreparedStatement ps = con.prepareStatement(qury);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                String Sid = String.valueOf(rs.getInt("Sid"));
                String fName = rs.getString("fName");
                String lName = rs.getString("lName");
                String tel = rs.getString("tel");
                String gender = rs.getString("gender");
                String age = rs.getString("age");
                String city = rs.getString("city");
                String cName = rs.getString("cName");
                String cTeacher = rs.getString("cTeacher");
                String cStart = rs.getString("cStart");
                String cEnd = rs.getString("cEnd");
                String cOffers = rs.getString("cOffers");
                String cCost = rs.getString("cCost");

                String tData[] = {Sid, fName, lName, tel, gender, age, city, cName, cTeacher, cStart, cEnd, cOffers, cCost};
                DefaultTableModel tbmodel = (DefaultTableModel) jTableShowStudent.getModel();

                tbmodel.addRow(tData);

            }
        } catch (Exception e) {
        }

    }
//     public void search(){
//         try {
//            String qury = "SELECT *FROM student where Sid=?";
//            PreparedStatement ps = con.prepareStatement(qury);
//            int id=Integer.parseInt(jTextFieldShowstudentSearch.getText());
//            ps.setInt(1, id);
//            ResultSet rs = ps.executeQuery();
//             if (rs.next()==false) {
//                 
//             }else{
//                 String Sid = String.valueOf(rs.getInt("Sid"));
//                String fName = rs.getString("fName");
//                String lName = rs.getString("lName");
//                String tel = rs.getString("tel");
//                String gender = rs.getString("gender");
//                String age = rs.getString("age");
//                String city = rs.getString("city");
//                String cName = rs.getString("cName");
//                String cTeacher = rs.getString("cTeacher");
//                String cStart = rs.getString("cStart");
//                String cEnd = rs.getString("cEnd");
//                String cOffers = rs.getString("cOffers");
//                String cCost = rs.getString("cCost");
//
//                String tData[] = {Sid, fName, lName, tel, gender, age, city, cName, cTeacher, cStart, cEnd, cOffers, cCost};
//                DefaultTableModel tbmodel = (DefaultTableModel) jTableShowStudent.getModel();
//
//                tbmodel.addRow(tData);
//             }
//         } catch (Exception e) {
//         }
//     }

//    public void showstudent2() {
//
//        try {
//
//            String qury = "SELECT cName ,cTeacher ,cCost ,cTime FROM cours";
//            PreparedStatement ps = con.prepareStatement(qury);
//            ResultSet rs = ps.executeQuery();
//            if (rs.next()) {
////                String id = String.valueOf(rs.getInt("Tid"));
//                String cName = rs.getString("cName");
//                String Cteacher = rs.getString("cTeacher");
//                String Ccost = rs.getString("cCost");
//                String Ctime = rs.getString("cTime");
//
//                String tData[] = {null, null, null, null, null, null, cName, Cteacher, Ccost, Ctime};
//                DefaultTableModel tbmodel = (DefaultTableModel) jTableShowStudent.getModel();
//
//                tbmodel.addRow(tData);
//
//            }
//        } catch (Exception e) {
//        }
//
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableShowStudent = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextFieldShowstudentSearch = new javax.swing.JTextField();
        jComboBoxSelectSearch = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTableShowStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fiste Name", "Laste Name", "Tel ++", "Gender", "Age", "City", "Cours Name", "Cours Teacher", "Cours Start", "Cours End", "Cours Offers", "Cours Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableShowStudent);

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldShowstudentSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldShowstudentSearchActionPerformed(evt);
            }
        });
        jTextFieldShowstudentSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldShowstudentSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldShowstudentSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldShowstudentSearchKeyTyped(evt);
            }
        });

        jComboBoxSelectSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sid", "fName", "gender", "cName" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Search By :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("List Of Student");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jComboBoxSelectSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jTextFieldShowstudentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(441, 441, 441)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxSelectSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldShowstudentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UserHome us = new UserHome();
        us.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldShowstudentSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldShowstudentSearchKeyReleased
        try {
         String selection = (String) jComboBoxSelectSearch.getSelectedItem();
            String qury = "select  *from student where "+selection+"=?";
//           System.out.println(qury);
            PreparedStatement ps = con.prepareStatement(qury);
            ps.setString(1, jTextFieldShowstudentSearch.getText());
            ResultSet rs = ps.executeQuery();

            jTableShowStudent.setModel(DbUtils.resultSetToTableModel(rs));
            
            String valueOfTxtF = jTextFieldShowstudentSearch.getText();
            if(valueOfTxtF.equals("")){
                showStudent1();
            }

        } catch (Exception e) {
        }
//        DefaultTableModel table = (DefaultTableModel) jTableShowStudent.getModel();
//        String search = jTextFieldShowstudentSearch.getText().toLowerCase();
//        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
//        jTableShowStudent.setRowSorter(tr);
//        tr.setRowFilter(RowFilter.regexFilter(search));
           

    }//GEN-LAST:event_jTextFieldShowstudentSearchKeyReleased

    private void jTextFieldShowstudentSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldShowstudentSearchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldShowstudentSearchKeyPressed

    private void jTextFieldShowstudentSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldShowstudentSearchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldShowstudentSearchKeyTyped

    private void jTextFieldShowstudentSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldShowstudentSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldShowstudentSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxSelectSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableShowStudent;
    private javax.swing.JTextField jTextFieldShowstudentSearch;
    // End of variables declaration//GEN-END:variables
}
